name: FLZ
favicon: null
layout_spectrum: 0.55176
typography_spectrum: 0.295
title: 'FLZ - Aprende a ser feliz... ahora!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f39e00'
    - '#3fa1b7'
    - '#ffffff'
    - '#2c1f00'
    - '#7f5300'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
